apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
data:
  PORT: {{ .Values.env.PORT | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}