apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
type: Opaque
data:
  APP_SECRET: {{ .Values.secret.APP_SECRET | b64enc | quote }}