apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
data:
  BACKEND_URL: {{ .Values.env.BACKEND_URL | quote }}
  PORT: {{ .Values.env.PORT | quote }}